spring:
  application:
    name: kafka-consumer

  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    username: test_user
    password: test_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update #validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: vtb-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      properties:
#        spring.json.trusted.packages: "*"

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} – %msg%n"
  level:
    com.vtb.kafkaconsumer: INFO

app:
  kafka:
    topic: test-topic
    concurrency: 3